### ISSUE TITLE
Results?

### ISSUE THREAD

**Issue by taylorbrooks** [sdogruyol/kemal-showdown#4]
What are the results of the showdown? Curious to see how Kemal performs against Phoenix.

**Comment by sdogruyol** [comment]
@taylorbrooks actually i haven't completed this yet 😢 Let me see if i can do a complete run this weekend.

**Comment by oltmannsdaniel** [comment]
@sdogruyol I will update the whole stuff in here and test it with my Machine (I7-6700K, Samsung 250GB SSD, 16GB DDR4 RAM).

The pull request will come soon.
