### ISSUE TITLE
Merging our effort

### ISSUE THREAD

**Issue by waghanza** [sdogruyol/kemal-showdown#6]
Hi @sdogruyol, 

I've found this project, and it's quite similar to this big one
https://github.com/the-benchmarker/web-frameworks

> DISCLAIMER : I'm the main maintainer

Regards,

PS : I think `martini` is **dead**

**Comment by sdogruyol** [comment]
@waghanza great job!

I'll try to update Kemal and Crystal to the latest 👍 And also try running with parallelism support
